### ISSUE TITLE
Missing devices after integration

### ISSUE THREAD

**Issue by tmorse305** [magico13/ha-emporia-vue#133]
Hi,

After integration, I can only see 7 devices.  My setup has 5 plugs and a Vue.  I can see all of the plugs (sensor & switch), the main Vue device but only one of the 16 channels.  I can see channel 16 only.  The sensors are reporting correct power data so I am connected.  Any suggestions?

Thank you.

**Comment by magico13** [comment]
Device population happens when the integration starts up, so you could try reloading the integration or restarting Home Assistant so that runs again. If the different devices still don't show up then check the logs to see if there are any errors related to this integration. The current beta/pre-release build may also have fixes in it that could help.

**Comment by tmorse305** [comment]
Thank you for your reply.  I tried a restart to HA last night after the integration but it did not help.  However I just tried it again and success!  Thank you for developing this integration!

**Comment by magico13** [comment]
Sounds good. It's odd to me that it didn't load them all the first time, since that all happens from a single API call, but I've seen inconsistencies with the API before so maybe it's just that. If you see any other issues let me know, thanks!
