### ISSUE TITLE
Usage by Second not displayed as an entity

### ISSUE THREAD

**Issue by iSynthetixx** [magico13/ha-emporia-vue#136]
The usage by the second is not an available entity to display in home assistant.

**Comment by magico13** [comment]
Emporia does not allow us to use the seconds-level API because it results in too many requests. It used to be supported but they explicitly asked us to remove it, so it is unlikely that it will be supported again. If you want that fine of sensor readings you'll have to install ESPHome on the Vue instead so you can get local access, but that also removes the connection to the cloud and requires physical changes to the device. That's not documented here but you can find it through Google.
