### ISSUE TITLE
second entity

### ISSUE THREAD

**Issue by chochobo78** [magico13/ha-emporia-vue#147]
Is it possible to integrate second-based sensors?

**Comment by magico13** [comment]
Unfortunately because we're limited to only about 2000 requests per day the seconds-level sensor isn't feasible. If you want that level of data you'll have to swap to a local option, either a different device or flash a custom firmware to the Vue. Here's a great guide for flashing ESPHome onto the Vue2, it's definitely involved but is the best way to get nearly live data into Home Assistant: https://gist.github.com/flaviut/93a1212c7b165c7674693a45ad52c512
