### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by Tyboeski** [magico13/ha-emporia-vue#184]
Keep getting unexpected error when I try to login.

**Comment by magico13** [comment]
This is typically due to invalid credentials. Check the casing on your username and password, I believe the email/username should be all lowercase but the password is case sensitive. If that doesn't resolve it then check the logs for a more detailed error message and consider logging into the Emporia web dashboard with the same username/password to ensure you're using the correct login info https://web.emporiaenergy.com

**Comment by Tyboeski** [comment]
Thanks having the initial letter in the email capitalized was my issue. It works now thank you so much
