### ISSUE TITLE
Vue Gen 2 support ?

### ISSUE THREAD

**Issue by mime29** [magico13/ha-emporia-vue#196]
I installed this amazing HACS + Integration. Thx for the nice work.
But I m facing a problem with the reported values.
they are reported as cummulated values it seems in the DB.

Is it because I'm using Vue Gen 2 or is it actually normal and maybe I'm missing some settings? -> In which case it would be nice to add it to the Readme.md

<img width="400" alt="image" src="https://user-images.githubusercontent.com/2211828/234791559-912f8954-cb14-4230-9177-9ab247a6d402.png">

Values should increase/decrease overtime but in Grafana and InfluxDB, the received values keep increasing.

**Comment by magico13** [comment]
It may depend in part on which sensors you're working off of. The 1Min sensors are power measures, specifically the average power over a one minute period (slightly delayed by a minute or two). The 1Day and 1Month sensors are energy sensors that reset daily/monthly respectively and will generally increase until their reset. You mention Influx and Grafana rather than the standard Home Assistant stuff I'm used to, so there could also be something messed up between Home Assistant and those.

**Comment by mime29** [comment]
![image](https://user-images.githubusercontent.com/2211828/235198049-f40e5288-d8c8-4782-a094-b429b6305cd2.png)
Basically I have access to those 2 sensors in Grafana.

Also I think I "fixed" the increasing value issue if what I get is a cumulated value for each "tick" (It seems to match your description in the comment)
![image](https://user-images.githubusercontent.com/2211828/235198353-1200571d-d186-4e61-8e59-7c224531a3a4.png)

But for some sensors it seems I get negative values.
Thanks a lot for spending the time on this issue by giving feedbacks.

**Comment by mime29** [comment]
It seems I only get 1 month and 1 day measurement for some reasons.
