### ISSUE TITLE
Weekly utility meter sensor

### ISSUE THREAD

**Issue by kenwiens** [magico13/ha-emporia-vue#222]
Emporia integration doesn't provide a weekly utility meter (that I can see).  I tried to create one using the utility meter helper, but I can't find a summation sensor for Emporia either.  I tried to do it using the 1min UM as the source for a weekly Utility Meter  (and indicating that the source was NET - ie could go up and down) - but then I just got a negative weekly number.

Is there a way to develop a weekly sensor?  I have considered using multiscrape and the web interface for Emporia Vue - but would rather not go down that path if it wasn't necessary.

**Comment by magico13** [comment]
The energy dashboard calculates weekly data but I'm not sure that it exposes that in an easily consumable way outside of the dashboard. You may be able to do something with the statistics, which is what the energy dashboard is based on, but I'm not sure exactly how that would work. You could also do something with the Emporia API through PyEmVue. You might be able to use the utility meter helper with the Monthly sensor which will only reset once a month, rather than the Daily sensor's more frequent resets.

**Comment by kenwiens** [comment]
I now use a series of automations, where I add the Emporia daily totals together for the week - for prior days in the week, and the minute sensor gets added in throughout the current day.  This seems to work and fortunately I have lots of available CPU cycles :-).  At the end of the week I store the accumulated kWh in a helper called "Last Week" and then reset my weekly counter to 0.

**Comment by kenwiens** [comment]
Manual work around. Please see my last comment
