### ISSUE TITLE
Change Minutes to second refresh time

### ISSUE THREAD

**Issue by pleeplow20** [magico13/ha-emporia-vue#24]
I am seeing if it's possible to change the refresh time of each sensor

**Comment by magico13** [comment]
Right now it's hard coded to one minute but I can look into making that configurable. The API itself only has 1 second or 1 minute average available (plus less frequent ones) so I defaulted to one minute to keep the number of requests reasonable. 

An issue if it were set to 15 seconds for instance, it would probably only get the 1 second usage each refresh and not the average over those 15 seconds, as opposed to with the one minute taking into account the average usage over that time. The only way to do the average would be to get all of the one second data over that time period, which is an option in the API, and then averaging it manually. Sorta just thinking out loud.

**Comment by atcd2020** [comment]
> 
> 
> Right now it's hard coded to one minute but I can look into making that configurable. The API itself only has 1 second or 1 minute average available (plus less frequent ones) so I defaulted to one minute to keep the number of requests reasonable.
> 
> An issue if it were set to 15 seconds for instance, it would probably only get the 1 second usage each refresh and not the average over those 15 seconds, as opposed to with the one minute taking into account the average usage over that time. The only way to do the average would be to get all of the one second data over that time period, which is an option in the API, and then averaging it manually. Sorta just thinking out loud but that might be an option I can look into.

Thank you keep me in the loop because I am making a "Smart RV" and so each second or even every 15 second is crucial to have that info

**Comment by trekb** [comment]
Hi,

Thanks for the great work on this integration.

Having the capability of reading the power usage in one second interval is especially useful for the creation of automations.

I am currently looking at the possibility of doing an automatic power control based on power usage, turning off automatically devices if the total power usage reaches the limit.

Regards

**Comment by atcd2020** [comment]
> 
> 
> Hi,
> 
> Thanks for the great work on this integration.
> 
> Having the capability of reading the power usage in one second interval is especially useful for the creation of automations.
> 
> I am currently looking at the possibility of doing an automatic power control based on power usage, turning off automatically devices if the total power usage reaches the limit.
> 
> Instead of changing the minutes to seconds, you should add a "seconds" entity.
> 
> Regards

I agree that would be nice

**Comment by chanders** [comment]
Thank you so much @magico13 for the great work you have put in to this. I am also working on automations that are dependent on power usage and having per second updates would make that work much better than waiting an extra minute to trigger the automation. 

Again, the only reason I bought this system was because of your integration :) Thanks a mil!

**Comment by magico13** [comment]
I'll try to get back onto this this weekend. I had it working but was trying to get it to be configurable so you can enable/disable the second, minute, daily, and monthly sensors during the setup. That way you can enable what you'll need and I can default to not doing 1 second unless you opt-in. I feel like that's the best/simplest option since I don't want to hammer their API from a bunch of different installs and get on their bad side ;) We're talking about 86,400 calls a day vs 1,440 so I want to be a bit careful before releasing that into the wild, as you can imagine.

**Comment by trekb** [comment]
Emporia should allow local access to the power readings. One second readings for sure will hammer their API.

Meanwhile I bought other power meter that allows local readings and is working great. Did some automation using Node Red to control de house power usage by turning off some heaters and AC if the power usage exceeds the maximum allowed. Since then no more circuit breaker disconnect due to excessive power consumption.

**Comment by atcd2020** [comment]
So I got the Seconds sensors to show up on all of my emporia devices plus I was able to change the update interval to 10 seconds but any lower the sensors stop working

**Comment by magico13** [comment]
> Emporia should allow local access to the power readings. One second readings for sure will hammer their API.

They pull more info per second when you leave the app open so it should be fine. They're using AWS and can easily scale up if needed.

I do agree that it would be nice to have local readings available but that won't happen from them unless they go out of business (and even then that's iffy). It would be possible to overwrite the current firmware with an open source one but you'd lose the ability to push data into their cloud so their app would stop working.

> So I got the Seconds sensors to show up on all of my emporia devices

I haven't pushed the code up for this yet so I'm curious how you're doing that. All the code right now pulls data at one minute intervals and specifically asks for the one minute average, the new code has a separate one second refresh block and asks for the one second usage.

**Comment by atcd2020** [comment]
I read up on your other project PyEmVue and learned how that works, and I adjusted one of the py files in the emporia_vue folder, and I am open to a more in-depth conversation on zoom or discord.

**Comment by chanders** [comment]
> I'll try to get back onto this this weekend. I had it working but was trying to get it to be configurable so you can enable/disable the second, minute, daily, and monthly sensors during the setup. That way you can enable what you'll need and I can default to not doing 1 second unless you opt-in. I feel like that's the best/simplest option since I don't want to hammer their API from a bunch of different installs and get on their bad side ;) We're talking about 86,400 calls a day vs 1,440 so I want to be a bit careful before releasing that into the wild, as you can imagine.

Thanks much for looking into this. Even a 10sec request is not bad as I am sure this will only be applied to some sensors and not all.  Will look out for the update!

**Comment by magico13** [comment]
So I've checked this into master but am going to let it run for a day or two on my instance to try to get a feel for the stability. There might also be concerns with inflating the database so I might set up some documentation discussing excluding those sensors from the recorder.

To use this now during the "beta" phase you can reinstall with HACS and set the version to "master". Then you'll have to delete the current integration, restart Home Assistant, then install the integration again to enable the 1 second sensor at install time. Some of your existing sensors and sensor history might get messed up if you've changed the names in the Emporia App or have been using this addon for long enough that the naming scheme has changed. If you just update without deleting the integration you can't enable the 1 second sensors (or disable the one minute/day/month sensors) but it should otherwise still function as before.

**Comment by masteryodha** [comment]
> Emporia should allow local access to the power readings. One second readings for sure will hammer their API.
> 
> Meanwhile I bought other power meter that allows local readings and is working great. Did some automation using Node Red to control de house power usage by turning off some heaters and AC if the power usage exceeds the maximum allowed. Since then no more circuit breaker disconnect due to excessive power .

@trekb I know this is a bit offtopic but what other power meter did you buy for local readings ?

**Comment by trekb** [comment]
> @trekb I know this is a bit offtopic but what other power meter did you buy for local readings ?
Shelly EM

**Comment by magico13** [comment]
Checked in with the latest release.
