### ISSUE TITLE
1 min sensor doesn't catch spikes in power

### ISSUE THREAD

**Issue by cliffjao** [magico13/ha-emporia-vue#244]
The 1 minute sensor doesn't catch spikes in power but the Emporia app does. In the example below, there's a spike up to 110 W at around 9:20PM but the HA axis below tops out at 18W.

![Screenshot_20240117-081855](https://github.com/magico13/ha-emporia-vue/assets/5115073/f84e1ab7-b0c3-41aa-a5a7-92d06e643b8d)

![Screenshot_20240117-081922](https://github.com/magico13/ha-emporia-vue/assets/5115073/b37fe7c0-9bfb-415f-a6e5-cca80c9afa50)

**Comment by magico13** [comment]
Double check the data in Home Assistant. You're looking at the statistics view, not the raw view, which filters the data into buckets. Click the Show More option and see if the spike shows up there. 

It may also not show up since Home Assistant is showing the history of the data it's received when you view historical data, but the Emporia app queries their database which can receive updates for past data and doesn't just return the latest info. In Home Assistant we can't update past data, so if the spike is a correction to past data in the Emporia database there's no way we can capture it.

**Comment by npstewart87** [comment]
I noticed there's a 1 second sensor in the config files but I've never seen the 1 second sensor show up as an entity. Was this intentional ?

**Comment by Esprit1st** [comment]
Emporia days that the 1s sensor shouldn't be used for an extended time because it puts stress onto the server. So using that server in HA is not a great idea, since it would poll non-stop 24/7. It's likely Emporia wouldn't be happy and eventually act in an unfavorable way to the HA community. (Just my thoughts!)On Jan 22, 2024 21:54, npstewart87 ***@***.***> wrote:
I noticed there's a 1 second sensor in the config files but I've never seen the 1 second sensor show up as an entity. Was this intentional ?

**Comment by alexwhittemore** [comment]
> Emporia says that the 1s sensor shouldn't be used for an extended time because it puts stress onto the server. So using that server in HA is not a great idea, since it would poll non-stop 24/7.

Seems like very compelling logic for Emporia to add a local channel option so this integration doesn't NEED to constantly poll ;)

**Comment by alexwhittemore** [comment]
Which, I've just gotten word, they absolutely and unequivocally will not do:
<img width="587" alt="image" src="https://github.com/magico13/ha-emporia-vue/assets/332827/0cef7061-5a6a-4852-9f91-d053f485cb18">
<img width="665" alt="image" src="https://github.com/magico13/ha-emporia-vue/assets/332827/34ee1251-1881-48b4-a815-4e69357cb632">

**Comment by warmfire540** [comment]
that's fine we don't need 1s sensors - we just want the 1m one to catch spikes

**Comment by DabblerIOT** [comment]
How it is working now, is how the emporia device works.   Nothing we can do to change this.   You could flash with esp32home and sort it out that way.
