### ISSUE TITLE
Update of Daily Histories Occurs while waiting for new Minute Data

### ISSUE THREAD

**Issue by DabblerIOT** [magico13/ha-emporia-vue#257]
Found while sorting out minute data issues.  Added a bunch of log noise in my running ha-emporia-vue for testing.

On startup two 1 minute callbacks are setup by ha-emporia-vue, one to update the minute data, and one to update the daily data from the last minute data.   Code ends up executing like this with the python "async" functions.

1 min Sensors Update (call back from ha scheduler)
http request made (waiting for response)
Daily Data Update Occurs (with old data) (call back from ha scheduler)
http request returns and data updates (about 200ms after request)

So if you see, the daily sensors are always getting 1 minute old data added in.  (Not huge deal, but not really correct).   Assuming this is being done to keep daily requests per instance under 2000 from request from api provider?

Cheers.

**Comment by magico13** [comment]
>  Assuming this is being done to keep daily requests per instance under 2000 from request from api provider?

Correct, it smooths out the 1D level data and since the energy dashboard is usually set up to use that it helps keep that a little more correct. I believe the 1D data only updates every few minutes on the API side (though I admit it's been a while since I tested/checked that). There's a call every 15 minutes or so to the API to correct any errors that might have built up, which sometimes introduces its own errors since the API can sometimes return old/incorrect/invalid data.

The timing could probably be improved to minimize those errors a bit more but I don't believe anyone has really commented on it being an issue until now.

**Comment by DabblerIOT** [comment]
Yes, not a big deal but just know that its accumulating 1 minute old data, instead of current data it just retrieved 200ms later.

**Comment by DabblerIOT** [comment]
Closing, kind of a nit pick.   But its not right for geeks.
