### ISSUE TITLE
Cannot add 1min sensor to Energy Dashboard

### ISSUE THREAD

**Issue by VE6FUK** [magico13/ha-emporia-vue#265]
energy dashboard will not allow 1min sensor to be added, as it is not in kWh.  Is this a possible change?  what about a 1hour sensor?

if the dashboard will only tell me what i use in a day, that doesnt give me the information I am looking for.

now, i dont have mine fully set up (waiting on utility), but am I reading this wrong?

**Comment by magico13** [comment]
The dashboard tracks energy, not power, so you must use a sensor that tracks energy. The ideal one to use is the 1 Day sensor, which is updated every minute but resets each day. The dashboard then tracks how that sensor changes throughout the day to group it into the separate hours. Home Assistant's ideal sensor for the dashboard is a sensor whose value measures total lifetime energy (always increasing) but is updated every second, eg what you'd get from a zigbee smart plug.

Long story short, pick the Day sensor because it's updated the most often. You can use the Month sensor but that is only updated hourly and won't always group data into the correct hours on the dashboard.

Here are some screenshots of how my dashboard looks using the Day sensor. for reference.

![image](https://github.com/magico13/ha-emporia-vue/assets/5289685/8e477960-048e-486a-8562-6780572cf494)
![image](https://github.com/magico13/ha-emporia-vue/assets/5289685/e15f9b19-222c-48fc-9fdb-8536813e214b)

**Comment by VE6FUK** [comment]
ohhhh. my apologies, i misunderstood what it was doing. i thought it meant it would only update one time per day.

**Comment by DabblerIOT** [comment]
You can make a similar dashboard using bar-card Lovelace card for power.   Power being watts, ex... what is going on RIGHT now... (or over the last minute). Could probably do something nicer looking with apex card, but I haven't tried yet.

![Screenshot 2024-03-15 at 8 33 47 PM](https://github.com/magico13/ha-emporia-vue/assets/159593555/278862bc-dae7-4516-90ac-38e0383a457c)
