### ISSUE TITLE
unable to login 

### ISSUE THREAD

**Issue by DaveR2419** [magico13/ha-emporia-vue#269]
Since update 4 days ago I've been unable to login through integration.
I'm able to login with my credentials in the emporia vue app.
Receive "unexpected error" when trying to login.

**Comment by slistre** [comment]
also experiencing this

**Comment by DaveR2419** [comment]
I use pihole, I will check it out.
Thanks

**Comment by slistre** [comment]
I also use a pihole with CF as fallback.

**Comment by slistre** [comment]
Looking at debug logs the error is:

ERROR (MainThread) [custom_components.emporia_vue] Could not authenticate with Emporia API

How can I clear my emporia credentials and reauthenticate?

**Comment by DaveR2419** [comment]
This error originated from a custom integration.

Logger: custom_components.emporia_vue.config_flow
Source: custom_components/emporia_vue/config_flow.py:79
integration: Emporia Vue (documentation, issues)
First occurred: 6:27:47 AM (1 occurrences)
Last logged: 6:27:47 AM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/emporia_vue/config_flow.py", line 79, in async_step_user
    self._abort_if_unique_id_configured()
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1943, in _abort_if_unique_id_configured
    raise data_entry_flow.AbortFlow(error)
homeassistant.data_entry_flow.AbortFlow: Flow aborted: already_configured

**Comment by magico13** [comment]
`Flow aborted: already_configured` means you've already got it set up, try restarting Home Assistant and see if it shows up. If you don't see it then uninstall and reinstall the integration to hopefully clear out the database entry for it.

If the `unexpected error` isn't due to incorrect credentials, then it might be due to the clock being out of sync like in #260. If you've got Home Assistant on a Raspberry Pi, dedicated computer, or VM then reboot it (don't just restart Home Assistant) which should force a time sync. If you're using docker then you may still need to reboot the host but you can't do that from within Home Assistant. You might be able to get it to sync without a reboot but that will depend on your operating system.

If that still doesn't do it, change your password to something basic, ie just letters and numbers, and try again. Special characters *should* be supported but sometimes they can cause unexpected issues. I've successfully used some common special characters but definitely haven't tested all that are possible.

@slistre if you changed your password then "Delete" the integration from the integrations page (not HACS) and add it again, you typically shouldn't lose any data but if you renamed anything in the Emporia app it might come back as a new entity. And if you remapped any switches to lights it might lose that custom mapping. If you didn't change your password then it could also be the time sync issue mentioned above.
![image](https://github.com/magico13/ha-emporia-vue/assets/5289685/b06c4e05-a442-4158-b34b-bc29fef9fa88)

**Comment by DaveR2419** [comment]
I did try rebooting the vm first, did not fix it. I then deleted the
integration, restarted HA and reinstalled, that worked. I had thought of
trying that first thing, but past issues with other integrations and api
did not work.

Thanks,
Dave

I will be sure to buy you a coffee for your contribution to the HA,
integration is very helpful!

**Comment by DaveR2419** [comment]
Reinstalled integration was the fix for my issue.
