### ISSUE TITLE
Query: Cant add 1 Min to Energy Dashboard Individual Devices?

### ISSUE THREAD

**Issue by andygodber** [magico13/ha-emporia-vue#272]
1D etc values are ok and can be tracked on the Energy Dashboard, but I cant add the 1Min variables.

Even though the Dashboard summarises by hour, I think the extra granularity might be useful.

![image](https://github.com/magico13/ha-emporia-vue/assets/1061812/0eddbb34-39c6-4714-8372-7d0c1e78f373)

**Comment by magico13** [comment]
The 1D sensors just mean that they reset daily, they are actually updated once a minute using the data from the 1 minute sensors, so you are already getting that level of granularity. The 1 minute sensors can't be added directly because they are Power sensors and the energy dashboard requires Energy sensors.

If you want a component that shows power coming in and going out at any moment, there are several custom cards for displaying that data that should work with the 1 minute sensors, but the energy dashboard itself doesn't support that sort of live view.

**Comment by DabblerIOT** [comment]
Not an issue.  Please post again if you don't understand explaination.
