### ISSUE TITLE
Update to HA core 2024.5.1 and Vue broke.  

### ISSUE THREAD

**Issue by mattlewis19** [magico13/ha-emporia-vue#277]
Just updated the HA Core to 2024.5.1 and the integration with Vue is no longer working.

**Comment by DabblerIOT** [comment]
what is hardware and other info?

have any logs?

**Comment by mattlewis19** [comment]
Hardware is a HP Prologic server running Hypervisor and HA OS.  
Core 2024.5.1
Supervisor 2024.04.4
Operating System 12.2
Frontend 20240501.0

Logger: custom_components.emporia_vue
Source: custom_components/emporia_vue/__init__.py:97
integration: Emporia Vue ([documentation](https://github.com/magico13/ha-emporia-vue), [issues](https://github.com/magico13/ha-emporia-vue/issues))
First occurred: 10:30:39 AM (3 occurrences)
Last logged: 10:44:06 AM

Could not authenticate with Emporia API

**Comment by magico13** [comment]
`Flow aborted: already_configured` usually is thrown when you're trying to set it up again but you already have it running. If you haven't rebooted, definitely recommend doing that first since that usually fixes any issues with the state machine trying to run two instances. If you have, you can try reloading the integration by going to the integration details and using the overflow menu.

![image](https://github.com/magico13/ha-emporia-vue/assets/5289685/342e8cc5-7049-4888-860a-2385bc28fd3d)

**Comment by mattlewis19** [comment]
Multiple reboots and reloads with no success, however I just deleted the hub and re-added it and that solved the problem.  Thanks for trying to help!!

**Comment by greymoment** [comment]
This entity is no longer being provided by the emporia_vue integration. If the entity is no longer in use, delete it in settings.

They are no longer providing readings by. the minute. I am very sad about this.

**Comment by Esprit1st** [comment]
Try reloading the integration and restarting HA. I had the same message and it fixed itself after a couple restarts.On May 13, 2024 08:05, greymoment ***@***.***> wrote:
This entity is no longer being provided by the emporia_vue integration. If the entity is no longer in use, delete it in settings.
They are no longer providing readings by. the minute. I am very sad about this.

**Comment by magico13** [comment]
> They are no longer providing readings by. the minute. I am very sad about this.

If the one-minute data failed to load properly, for example if the API is down or acting unreliable at startup, then those entities can fail to be created. That's another situation where a reload of the integration can fix it, but you might need to wait a bit for the API to stabilize itself first.

Sounds like the main problem for this issue is resolved so I'm going to close this.
