### ISSUE TITLE
Multiple Sensors and Energy Dashboard

### ISSUE THREAD

**Issue by mbhforum** [magico13/ha-emporia-vue#291]
Not sure if this is an issue or by design, but I am seeing 3 sensors for each breaker. What does each sensor represent?  If I want to integrate these sensors into HA's energy dashboard, which sensors should I pick and which radio option should?  ![image](https://github.com/user-attachments/assets/fb6d74b4-f26c-45d5-818a-41d820680633)

![image](https://github.com/user-attachments/assets/cdbeeedc-41f7-431d-abc7-bc66159b5db8)

**Comment by magico13** [comment]
They reset at different times, same as selecting the Minute, Day, and Month scales in the app. Minute is average power over a minute, the other two are energy used today or this month.

For the energy dashboard, pick the Day sensor since it has its value updated most frequently. The 1 minute sensor is power, not energy, so it won't be an option to choose from.

**Comment by magico13** [comment]
For the radio options for cost, that's asking about your electricity price. If it's a fixed number (eg 15 cents per kwh) then just use that number. Otherwise if you're on a time of use plan or it changes daily or something then you'll want to do some work to setup a sensor that gives the current price. 

Or if you don't care about cost tracking just select that option.

Also if it's not clear, for the overall usage from the grid you'll want to pick your main 1,2,3 device (and if you have solar then there's a TotalFromGrid and TotalToGrid to use instead, for the appropriate options). The other channels should be brought in as individual devices afterward.

**Comment by mbhforum** [comment]
Thanks!  Since Emporia is configured with my local utility we with the costss, I picked the same D sensor for costs, will that tell HA how much I am spending?

**Comment by magico13** [comment]
No, it will not. That information is not currently exposed to Home Assistant through the API.

**Comment by mbhforum** [comment]
Thanks.  So, I see there are also sensors for the entire electrical panel.  Since I have two, I created a Group in HA that uses the sum of both of those so I can track it via the Energy Dashboard.  The group sensor is adding up the total kWH properly in real time, but on the HA Energy dashboard, it shows 0.0. I realize this might be more of an HA issue than an issue with the integration, but how people are using this integration in that manner?

![IMG_0441](https://github.com/user-attachments/assets/7c5ca020-58c7-46d5-8ac1-5e5fcf59553e)
![IMG_0442](https://github.com/user-attachments/assets/6382c68b-7a17-4f10-b72d-bed56847ca6c)

**Comment by mbhforum** [comment]
Thanks for your help. In Home Assistant, I created a group sensor of both of my electrical panel sensors from Emporia.   I made this the source of my Energy Grid consumption, but for some reason, the data seems off.   Shows 7.25 kWH combined, but on another dashboard, the right kWH is represented.  What am I doing wrong?


![IMG_0452](https://github.com/user-attachments/assets/638d2ba2-c137-414b-9870-c4c73362fc36)
![IMG_0451](https://github.com/user-attachments/assets/ace71b01-8e31-46e6-83fd-20aeec327964)

**Comment by mbhforum** [comment]
I setup a HA helper group containing the two seperate panel readings.  It measured the kWh fine yesterday but today I woke up and saw a negative kWh number on my energy dashboard.  Any idea why this is happening?

![image](https://github.com/user-attachments/assets/0bcdb7a3-6b74-49f6-9e5b-8c93adf7a501)

![image](https://github.com/user-attachments/assets/e04cc78d-d2d6-4ff8-88c0-14a1d1618c48)

**Comment by magico13** [comment]
Make sure your timezone on your Home Assistant server matches the timezone you have set in the Emporia app for the devices. If they don't then the reset at midnight won't align correctly and it will see the drop back to 0 as negative usage.

**Comment by mbhforum** [comment]
Both are set to EST.  I read in the HA Reddit sub, someone else had the issue and they added all of these individual devices instead of the Panel as a whole.  I will see if that works and doesn't cause a negative value tomorrow.

**Comment by Esprit1st** [comment]
Do you not have the "MainsFromGrid" Sensor? That's what I used as a single sensor for the energy dashboard and it's been working perfect for about 2 years.On Jul 22, 2024 08:30, mbhforum ***@***.***> wrote:
Both are set to EST.  I read in the HA Reddit sub, someone else had the issue and they added all of these individual devices instead of the Panel as a whole.  I will see if that works and doesn't cause a negative value tomorrow.

**Comment by mbhforum** [comment]
> Do you not have the "MainsFromGrid" Sensor? That's what I used as a single sensor for the energy dashboard and it's been working perfect for about 2 years.On Jul 22, 2024 08:30, mbhforum ***@***.***> wrote: Both are set to EST. I read in the HA Reddit sub, someone else had the issue and they added all of these individual devices instead of the Panel as a whole. I will see if that works and doesn't cause a negative value tomorrow. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

I do not.  I only see 1D, 1MIN and 1MON sensors for each breaker and for each panel.  I also have a Balance sensor for each panel as well.  Lastly, I have a GEN2 version, not GEN3, not sure if that matters.

**Comment by Esprit1st** [comment]
I'm pretty sure you should see two MainsFromGrid sensors. I have two, a 1D and a 1MON. Sensor. I also have the gen 2 Vue.Just checking: you have the two big clamps around the main lines coming into your breaker box set up correctly.On Jul 22, 2024 11:49, mbhforum ***@***.***> wrote:

Do you not have the "MainsFromGrid" Sensor? That's what I used as a single sensor for the energy dashboard and it's been working perfect for about 2 years.On Jul 22, 2024 08:30, mbhforum @.> wrote: Both are set to EST. I read in the HA Reddit sub, someone else had the issue and they added all of these individual devices instead of the Panel as a whole. I will see if that works and doesn't cause a negative value tomorrow. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: @.>

I do not.  I only see 1D, 1MIN and 1MON sensors for each breaker and for each panel.  I also have a Balance sensor for each panel as well.  Lastly, I have a GEN2 version, not GEN3, not sure if that matters.

**Comment by mbhforum** [comment]
This is all I see.  Can you post a screenshot?

![IMG_0459](https://github.com/user-attachments/assets/09dcf780-80ea-434c-a3f6-31cac2fd0dd9)

**Comment by magico13** [comment]
The original poster appears to have two separate panels that both are connected to the grid, rather than the more typical single panel. They also do not appear to have solar, so no MainsFromGrid sensor. The `1,2,3` sensor is the correct one to use in that case. 

Having to add them both together is definitely an unusual situation and could be related to the energy dashboard dropping, since the dashboard will look at the last reset time and that won't probably be propagated from the base sensors. You might be able to change the helper from a Total to a TotalIncreasing type, so it resets automatically when it drops down, but that can have the occasional issue when the API is unstable.

**Comment by mbhforum** [comment]
I will see how the Helper group of all of the individual 1D sensors work on the energy dashboard tomorrow.  One thing also interesting I noticed is, the sum of the two electrical panels (Electrical Usage) so far today is 5kWh higher than the individual sensors (Total Electricity Helper Group).  Why the discrepancy?  

![IMG_0461](https://github.com/user-attachments/assets/13ff68ea-5ce9-4cd7-b6b4-60f102c71ac8)
![IMG_0460](https://github.com/user-attachments/assets/95ccca21-5459-4a1e-bd2d-160564f7ce68)

**Comment by DabblerIOT** [comment]
I have same setup, and am working fine sending just the mains 1d data from both mains like you had setup above.  I can't remember if it took a day before logs started looking correct.  Set it up a while ago.

![Screenshot 2024-07-22 at 7 40 05 PM](https://github.com/user-attachments/assets/b6108b0a-5b15-475f-be93-9ff5ad0d7fb6)

**Comment by mbhforum** [comment]
> I have same setup, and am working fine sending just the mains 1d data from both mains like you had setup above. I can't remember if it took a day before logs started looking correct. Set it up a while ago.
> 
> ![Screenshot 2024-07-22 at 7 40 05 PM](https://private-user-images.githubusercontent.com/159593555/351140521-b6108b0a-5b15-475f-be93-9ff5ad0d7fb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MzgyNTMsIm5iZiI6MTcyMTczNzk1MywicGF0aCI6Ii8xNTk1OTM1NTUvMzUxMTQwNTIxLWI2MTA4YjBhLTViMTUtNDc1Zi1iZTkzLTlmZjVhZDBkN2ZiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QxMjMyMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZmQyZDI0ODY2ODkyN2E4Yjc0NGY1ZjI0ZTkxYjNhMWMwNzEzNzdlNDU0NjlhODg2MzM2MGYwYTZlY2RiYjdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P0Dvd9xo9kO40BxBMErjRjlp1pyWNa_3CiNC0-6YSIs)

Thanks. This works for me too. The difference is, you put the panels in separately, where as I was trying to combine the panels to a Home Assistant helper group to try and make it a single entity. It's not a big deal as HA does the sum with Grid Total.

**Comment by DabblerIOT** [comment]
I did the same type of thing to combine circuits for my power view.. (how much I'm using NOW).  So I could like at 8 things rather than 32.  One thing I have noticed is how the updates happen in HA is one sensor updates first and I get a new total, and then the other updates shortly after and I get a second total.   If both are changing.   Maybe something with this is throwing the energy stuff off.   The startup of the energy stuff from memory was kind of squirrely for me, but after first day seems to be working fine.

![Screenshot 2024-07-24 at 7 58 35 AM](https://github.com/user-attachments/assets/5b148ec9-4be6-4555-8135-dfbb7a41d8b0)

**Comment by DabblerIOT** [comment]
@magico13 

Most new houses over 5000 sf in my area have split 400 amp service, meaning 2 200 amp panels connect out to the meter.

I know it sounds crazy to rest of the world.   That amount of space, and that amount of power for one family.  (Around Washington, DC).

**Comment by mbhforum** [comment]
> @magico13 
> 
> 
> 
> Most new houses over 5000 sf in my area have split 400 amp service, meaning 2 200 amp panels connect out to the meter.
> 
> 
> 
> I know it sounds crazy to rest of the world.   That amount of space, and that amount of power for one family.  (Around Washington, DC).
> 
> 
> 
> 

Correct. My house is over 5,000 square feet and was built two years ago with two 200 amp split panels.  In addition, my AC compressors and pool equipment is on a seperate panel where I now need to buy a third Emporia unit to measure that consumption.

**Comment by DabblerIOT** [comment]
I just monitored pool panel with 2 cts for sub-panel (mainly just pump and lights), and pool house (not much) with 2 cts for sub-panel (mainly lights at night).  Only real use for me is to notice if I left pump on higher speed from chemical treatment or having people over.   The current OmniLogic outage is killing me.  (they still aren't back up all the way).

Anyway if you are sorted out appreciate it if you would close issue.  (Or I can later). :)
