### ISSUE TITLE
Migrate Data

### ISSUE THREAD

**Issue by bugsysiegals** [magico13/ha-emporia-vue#321]
I have an Emporia Vue with 8 sensors in a 20 slot circuit panel (4 of these are dual pole).  I just purchases an Emporia Vue with 16 sensors and want to migrate the 8 sensor unit to my subpanel and install the new unit into the main panel.

This is easy enough but I'm wondering if there's a way to install the new sensors and migrate the data from the previous sensor to the new sensor so each circuit doesn't lose it's history?  I'm not sure if this would simply be a process of noting some ID's and then replacing those ID's with the new sensors once I've made the migration or something terribly more difficult?

**Comment by magico13** [comment]
The short answer is that I don't know of a simple way. The new Vue will show up as all new sensors in both the Emporia app and in Home Assistant because it has a different id. In theory you could copy/move the data in the Home Assistant database from the old entity to the new one but I've never tried that and I don't know how difficult it would be.

**Comment by bugsysiegals** [comment]
I read you can write down the current entity names, remove the integration, reboot, delete any left over entities, add the new Emporia, add the new sensors, rename them to the old sensor names, and then the history will be for the new sensors with old names. That said, I don’t know how to rename the new sensors … is it in entities or do I need to modify files … any idea?
