### ISSUE TITLE
Unable to use multiple accounts?

### ISSUE THREAD

**Issue by cybertimber2009** [magico13/ha-emporia-vue#329]
I originally had a Emporia Vue 3 connected in HA for my home.
I tried adding an additional Emporia View 3 to my HA to my parents home at their request to monitor something.
Everything was working OK until I rebooted, at which point only one or the other would work based on which was reloaded last.

I know it prompts for credentials when adding. Is that not persistent, and whichever credentials were used last try to be used for any Emporia devices after?

**Comment by magico13** [comment]
Only a single account is supported at the moment due to a number of architecture limitations that are difficult to rework. I actually thought it would block you from even trying to set up another one but I guess there's something missing to prevent that ahead of time.

Unfortunately at this time the only options I am aware of would be to set up a separate Home Assistant instance or to put both Vues under the same account.

**Comment by cybertimber2009** [comment]
Thanks for the clarification! 
I shall close :)
