### ISSUE TITLE
Possible to support multiple Vues

### ISSUE THREAD

**Issue by wreuvers** [magico13/ha-emporia-vue#36]
Hi Michael

Your integration is a LIFE SAVER!! I have a small Cay in the Bahamas (remote private island), and I use your integration to monitor what power I am using across different devices and divert excess power into either my PowerStore75 kWh (reclaimed Tesla Model 3 battery pack), PowerGrid30 kWh (my grid made from reclaimed Tesla Model S batteries) or my PowerSafe15 kWh (my batteries on my yacht). I recently added a second Vue (and about to add a third) - one for the yacht the other for another part of the island. Would it at all be possible to support more than one?

BTW, you are always welcome to stay on the Cay anytime you are in the area!! It would not be running so well without you!!!

Thanks
Wayne

**Comment by magico13** [comment]
It should automatically support multiple Vue devices as long as they're all in the same account. You may have to reboot home assistant or remove and readd the integration before it will find the others. Let me know if you have any issues with it. I haven't tested it with multiple Vues, just a gen 1 vue+expansion and a smart plug

**Comment by wreuvers** [comment]
Hi Michael

Yup, that worked - thanks!!! I now see all the items in the second Vue. When I first installed it, I missed the option to enable the 1s vue - how can I now enable those?

Thank you soo much for your help!
Cheers
Wayne

**Comment by magico13** [comment]
To enable the 1 second sensors you'd have to delete and re-add the integration since there isn't yet a way to modify the initial configuration after it's set up. Because all the sensors use a unique id any automations or visualizations should still work after you re-add it so you shouldn't lose anything by doing that.

I'd caution that the 1s sensors adds more load to their servers so unless you're planning on using it for automations or otherwise need the data that fine grained I wouldn't enable it just to have it. I'm tentatively planning on adding a way to reduce the polling frequency to every 2 seconds or 5 seconds or similar to help reduce the network traffic it would cause since I don't want to get on Emporia's bad side with this integration.

**Comment by wreuvers** [comment]
Aah, that makes sense. I'll wait for the 5s. 10s would be the best if that is at all possible, as that is frequent enough for sensors to switch and not a huge amount of overhead.

**Comment by magico13** [comment]
Closing this particular issue but if you want to track when the update interval is made configurable, that will be handled by issue #39
