### ISSUE TITLE
Allow specifying the update interval for the "instant" usage

### ISSUE THREAD

**Issue by magico13** [magico13/ha-emporia-vue#39]
Right now we retrieve the "instant" usage every one second when the "One Second Sensor" is enabled. Assuming each request actually happens once a second, that's at least 86,400 requests a day. With only a one minute update it's at least 1,440 requests a day which is substantially less. For most cases where you want updates more often than once a minute you may only need data every two seconds, or five seconds, or ten. For those examples we're looking at 43,200, 17,280, or 8,640 requests a day, all of which are considerably less than the one second update and put less stress on the Emporia APIs, something I'm sure they'd appreciate.

Goal: provide a way to set the update frequency for the instant sensor via the config flow. It is sufficient that it is set once during setup and can only be changed by deleting and readding the integration (until an options flow is set up to allow changing settings post-setup).

**Comment by shillingcl** [comment]
I agree this would be great if it's possible, but I can see some complexities with it too... For instance, when you pull the minute data, I believe it is providing you the "Mean" of that full minute of use.  If you were to only pull data every 15 seconds, you would just be pulling a snapshot of that one second, completely ignoring what happened for the other 14 seconds.  (Still workable, just something to consider)  

 I recently set up 2 units with 16 channels each.  Due to load concerns listed above, I standardized on the 1 Min reporting and it's more than sufficient for most of my monitoring in HA.  I do have one circuit, for my sump pump, that having more granular power detail would allow me to better monitor.  (i.e. count # cycles per minute)

As an alternative, would it be possible to use 1 Min as the default reporting for channels, but then have the option to specify a few channels that per second information can be pulled for?  Is there a significant performance benefit in that approach based on the way the data is accessed?   Thanks for all your work on this!

**Comment by magico13** [comment]
The way the API works, or at least the calls I'm using here, it returns data for all the different channels at once so it's easiest to update them all at the same time. The one minute call does indeed return the kwh usage over that period and then I multiply it to give the average kw rate, same as the app does. If I set it to update every 15 seconds I probably could get the total usage over the last 15 seconds and get the average rate, rather than just a snapshot, like with the one minute sensor but I'll need to experiment with that to be sure.

Even with the snapshot you'd be able to use it for automations for things that draw power for more than a few seconds but less than a minute. For instance I've got an automation that notifies me when the garage door opener is activated and that takes 15 seconds or so. It'd get a bit lost in the noise of the one minute sensor when it gets averaged out but it should be pretty obvious with a 5 to 10 second update as a sharp spike of known size for a moment.

**Comment by akballow** [comment]
Having an option for every 10 seconds even would make a big difference. I think every 1 second is just too much network activity for most use cases.

**Comment by fxstein** [comment]
Here is another thought: How about using the graph API every minute but request 1S data - If I understand correctly that should return 60 individual data points.

Most automation can live with 1 min data for sure. However forensics to check for behaviors after the fact often take 1S data. 

Would love to keep 1S data in InfluxDB for 365 days but have HA primarily work off 1MIN data.

I used to run an Eagle and a bunch of UBNT MFI sensors that both have a local API so I could pull it every second. Was hoping to be able to retire the MFI setup with Vue but the data side is not quite there yet.

**Comment by magico13** [comment]
When I looked into it before it didn't look like Home Assistant would allow me to import historical data. If you want to pull that data for historical purposes into InfluxDB, I recommend looking into VueGraf https://github.com/jertel/vuegraf

**Comment by magico13** [comment]
I didn't find any information about loading historical data unfortunately so I'm going to continue recommending vuegraf for historical analysis at the seconds level. Since this issue isn't really relevant anymore I'm going to close it.
