### ISSUE TITLE
Error after upgrade to 6.0

### ISSUE THREAD

**Issue by frumiousband** [magico13/ha-emporia-vue#54]
After upgrading to 6.0 I get the following error.

Retrying setup: Exception while setting up Emporia Vue. Will retry. Error communicating with Emporia API: an integer is required (got type NoneType)

**Comment by magico13** [comment]
Interesting. Do you have solar? Any other weirdness with your setup? I'd downgrade back to 0.5.0 for now since I won't be able to get to this until tomorrow

**Comment by frumiousband** [comment]
Yes, I do have solar. I downgraded back to 5.0 and things are back to
working. I am also using the Emporia Vue 16 sensor system  Emporia Smart
Home Energy Monitor with 16 50A Circuit Level Sensors | Real Time
Electricity Monitor/Meter | Solar/Net Metering - - Amazon.com
<https://www.amazon.com/gp/product/B08CJGPHL9/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1>

Also, this integration is great can't wait to get it in HA energy!

**Comment by frumiousband** [comment]
System info

[image: image.png]
Here is what is in the log.
2021-08-06 20:53:16 ERROR (MainThread) [custom_components.emporia_vue]
Error communicating with Emporia API: an integer is required (got type
NoneType)
2021-08-06 20:53:16 WARNING (MainThread) [custom_components.emporia_vue]
Exception while setting up Emporia Vue. Will retry. Error communicating
with Emporia API: an integer is required (got type NoneType)
2021-08-06 20:53:29 WARNING (MainThread) [homeassistant.components.onvif]
Couldn't connect to camera 'ANnke', but will retry later. Error: All
connection attempts failed
2021-08-06 20:53:31 ERROR (MainThread) [custom_components.emporia_vue]
Error communicating with Emporia API: an integer is required (got type
NoneType)
2021-08-06 20:53:31 WARNING (MainThread) [custom_components.emporia_vue]
Exception while setting up Emporia Vue. Will retry. Error communicating
with Emporia API: an integer is required (got type NoneType)
2021-08-06 20:53:53 WARNING (MainThread) [homeassistant.components.onvif]
Couldn't connect to camera 'ANnke', but will retry later. Error: All
connection attempts failed
2021-08-06 20:53:56 ERROR (MainThread) [custom_components.emporia_vue]
Error communicating with Emporia API: an integer is required (got type
NoneType)
2021-08-06 20:53:56 WARNING (MainThread) [custom_components.emporia_vue]
Exception while setting up Emporia Vue. Will retry. Error communicating
with Emporia API: an integer is required (got type NoneType)
2021-08-06 20:54:36 WARNING (MainThread) [homeassistant.components.onvif]
Couldn't connect to camera 'ANnke', but will retry later. Error: All
connection attempts failed
2021-08-06 20:54:41 ERROR (MainThread) [custom_components.emporia_vue]
Error communicating with Emporia API: an integer is required (got type
NoneType)
2021-08-06 20:54:41 WARNING (MainThread) [custom_components.emporia_vue]
Exception while setting up Emporia Vue. Will retry. Error communicating
with Emporia API: an integer is required (got type NoneType)

**Comment by cromulent1** [comment]
Thank you for your work on this.  It's pretty amazing.  Adding another data point.  I got the same error, but do not have solar.  I have 5 emporia vue 2s monitoring 68 hots.  Other than the large number of monitored circuits my Home Assistant setup is pretty vanilla since I'm just getting started with HA.  These are the only errors I'm seeing in my log (not sure if the runner.py one is related):

Exception while setting up Emporia Vue. Will retry. Error communicating with Emporia API: an integer is required (got type NoneType)
9:17:12 AM – (WARNING) Emporia Vue (custom integration) - message first occurred at 9:01:38 AM and shows up 15 times
Error communicating with Emporia API: an integer is required (got type NoneType)
9:17:12 AM – (ERROR) Emporia Vue (custom integration) - message first occurred at 9:01:38 AM and shows up 15 times
Error doing job: Unclosed connection
9:14:11 AM – (ERROR) runner.py - message first occurred at 9:06:58 AM and shows up 2 times

Thanks!

**Comment by magico13** [comment]
Do either of you happen to have any channels/sensors that aren't attached? My current guess is that it's the method that gets the last reset time that's failing because the timestamp data isn't being returned.

If you could please do a reinstall in HACS and select the version "master", I pushed up a change that should fix it if the problem is indeed the timestamp data being empty.

**Comment by cromulent1** [comment]
Yes, I have unused ports on one of my Vue 2 units.  I reinstalled using master and that appears to have fixed it.  No more errors in the logs and I can see the sensors in the energy configuration screen.  Thank you!

**Comment by cromulent1** [comment]
Just realized that because I have 400A service that is split into two 200 A panels I have no way to tell HA that I want to combine 2 sensors instead of just monitoring one.  I'll put it in as a feature request.  Thanks again for your work on this, I'm blown away by it.

**Comment by magico13** [comment]
> Just realized that because I have 400A service that is split into two 200 A panels I have no way to tell HA that I want to combine 2 sensors instead of just monitoring one

You should be able to select two sensors to monitor as the input within the energy dashboard, which might help get you closer to what you're looking for.

**Comment by cromulent1** [comment]
> You should be able to select two sensors to monitor as the input within the energy dashboard, which might help get you closer to what you're looking for

Right you are!  I didn't realize I could select multiple sensors.  I only see the 1D, and 1MON sensors.  Should I also see the 1MIN?

**Comment by magico13** [comment]
Use the 1 Day sensors. Home Assistant's dashboard is a little funky because instead of showing current power it shows the daily energy. You can only pick energy sensors (day and month from this integration) not power sensors. Even though it looks like Tesla's power monitoring diagram it doesn't work quite the same way.

**Comment by magico13** [comment]
Officially released 0.6.1 to address this. Let me know if you notice any other issues, thanks!
