### ISSUE TITLE
Balance value(s) as a sensor

### ISSUE THREAD

**Issue by codycato** [magico13/ha-emporia-vue#55]
I have more than 16 breakers, so there's alway a remaining balance; can we get that as a sensor?
label: Feature Request @

**Comment by skynet01** [comment]
Agreed, or at least have it as an energy sensor so we can see it on our energy dashboard

**Comment by magico13** [comment]
This is something I've wanted myself as well so I'll probably add it. In order to do it I need to actually parse the device tree and understand what devices are children of others. For one Vue and some circuits this is easy but when you add the smart plugs as children of a circuit or have multiple vues that may or may not be nested then it's not a straightforward calculation because each channel reports the full usage, ie you'd double up if you just added everything up.

**Comment by skynet01** [comment]
Ah, i thought they would have the balance available through the API. Maybe initially the plugs can be ignored and it's just (Total Power)  - (All channels ) .. although total power sometimes goes negative for people with solar..

**Comment by magico13** [comment]
So the latest API changes (see #61) actually made the balance sensor populate automatically, so I guess this is done!
