### ISSUE TITLE
Not showing in integrations after install

### ISSUE THREAD

**Issue by photomatix18** [magico13/ha-emporia-vue#6]
Looking forward to trying this out! Only problem is I can seem to find it listed in the integrations after I installed it using HACS. Any suggestions? I checked my /config/custom_components folder and it installed the files, so I'm not sure why it's not showing up.

**Comment by magico13** [comment]
Hmm, that's definitely strange. What version of Home Assistant are you on? Do you see anything in the logs under the Developer Tools? 
When the integration starts up there are some warnings that show up in there because I need to move some logic around, but that should indicate whether it's starting up correctly. That warning might not show up until it's configured though but if there's something preventing it from being configured that would hopefully be logged as well.

**Comment by photomatix18** [comment]
I'm running 0.111.0. This is odd; so I just restarted the system again and
now it's showing up. I restarted HA probably a dozen times last night with
no success. Got logged in and now it's working fine. Good work on the
integration!

**Comment by magico13** [comment]
I know that 0.111.0 changed up how the interface and integrations load so that the integrations load in the background so maybe that's related. I haven't installed 0.111.0 yet to test with it, I'm still on 0.110.0. Glad to hear that it's working now!

**Comment by pmd5700** [comment]
I'm having the same issue. I'm on HA 0.111.1. The only log I see is this: You are using a custom integration for emporia_vue which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
