### ISSUE TITLE
Emporia API Updates 

### ISSUE THREAD

**Issue by magico13** [magico13/ha-emporia-vue#61]
Looks like the API had some updates, will try to update as fast as I can, sorry to anyone affected.

**Comment by Berzerker** [comment]
If they're not going to give us a local-only option (which it really sounds like they won't), it would be nice if they at least alerted us to API changes.

**Comment by magico13** [comment]
This is based on an unofficial API so they're under no obligation to warn us or to even allow us to keep piggybacking off of the app API. I understand the frustration though. It appears as if they made this change last week and then turned off the old API methods today so I will try to be more diligent about checking the API after app updates in the future so we can transition off the old API before it shuts down.

**Comment by magico13** [comment]
Working now with v0.6.3. Time to get back to my day job, this was not how I planned on spending my lunch break (plus an extra hour and a half), haha. The Balance sensor shows up now as a result of this change and I may need to make some additional changes but the sensors are populating again.

**Comment by Berzerker** [comment]
Working for me as well, for anyone else reading this, make sure to give it about 5 minutes after updating, and reload the integration in HA (*not* HACS). That seemed to do the trick for me.

**Comment by tteck** [comment]
@magico13 Thank you for all of your hard work!

**Comment by robtheone** [comment]
I just noticed the "balance" sensors this morning - 1D, 1MIN, and 1MON, which is GREAT, and a feature I had been hoping for.  I have 3 emporia systems total, all with the same customer number, but the BALANCE sensor names appear different on Home Assistant than other normal sensors.  For normal sensors, it appears that the names are pulled from the Emporia app, and I can see the name of the sensor in the "Entity ID" field, BUT for the BALANCE sensors, I do not provide a name for the sensor in the emporia app, so it is just named "sensor.power_balance_balance_1d" for example, and having 3 systems, Home Assistant (I assume) is naming them for all 3 systems as follows, for example, the 1 day sensors:

sensor.power_balance_balance_1d
sensor.power_balance_balance_1d_2
sensor.power_balance_balance_1d_3

I assume I can figure out which sensors belong to which system by comparing numbers to the app, but if the naming convention can be changed, that would be easier. I can see in the HA logs where it says "Adding channel for channel 19777-Balance", and the same for the other 2 systems, 39111-Balance, and 39222-Balance, which these numbers correlate to identify each system.

The logs also show the following when importing in the minute sensor data 19777-Balance-1MIN': {'device_gid': 19777, 'channel_num': 'Balance.

Since it seems that the device_gid numbers are being imported in already, would it be possible to continue with the same naming convention for the balance sensors as for other sensors in a future update so that it is easier to distinguish which sensor belongs to which system?

Thanks so much!
![balance_sensor_names](https://user-images.githubusercontent.com/29762174/130094646-e302ac64-fffe-4fc1-8a7f-af601537ff77.JPG)

**Comment by magico13** [comment]
I agree that the balance sensor naming is unfortunate. The normal naming scheme is "Power {Name} {ChannelNum} {Scale}" and for the balance sensors the Name and ChannelNum are both "Balance". The internal unique id is built off the device id and the channel number which ensures uniqueness.

What you can do without changes is figure out which is which and rename the sensors within Home Assistant to something more useful. I can look into handling Balance as a special case, separate from the normal naming scheme, so the name would include the name of the Vue that it's associated with.
