### ISSUE TITLE
Power Mains from and to Grid doesn't plot in Energy

### ISSUE THREAD

**Issue by yodashut** [magico13/ha-emporia-vue#67]
As of August 19th, the Energy app in Home Assistant doesn't plot energy from grid or to grid from the HA sensor...it just shows nothing in the plots.

When I pull up the entities and click on their history, the data shows to be plotting just fine in the log, but Energy doesn't seem to be able to pull it thru.

I'm wondering if maybe there is a units issue?  Is there any way to change the units in the code from kWh to Wh?

**Comment by magico13** [comment]
Someone else has mentioned that the "last reset" was causing issues with how data is being summed up so I'm assuming that's the issue. Unfortunately there's nothing you can change to fix that but I'm going to be updating this in a few days to remove the last reset since home assistant has decided they don't actually need it

**Comment by Zyell** [comment]
@yodashut I edited this one of the plugin files here: https://github.com/magico13/ha-emporia-vue/blob/ededdc2de861d4cc8c0b87fb91b7fccffb85a78a/custom_components/emporia_vue/__init__.py#L276 in my homeassistant installation.  I replaced this reset_datetime with the following for the Day case:
```python
reset_datetime = datetime.now().replace(hour=0, minute=0, second=0, microsecond=0, tzinfo=timezone(timedelta(hours=<'your utc offset in hours'>))).astimezone(timezone.utc).replace(tzinfo=None)
```
The timestamp has to be in UTC because the statistics table requires this and it won't be converted from your timezone to UTC at the time it is written to the database.

This won't fix some invalid calculations on homeassistant's part.  However, I look at the statistics_meta table to find the sensor id numbers I care about correcting.  Then I execute a script to correct the database calculation from a jupyter notebook (I used the Jupyter lab addon but you could also use the app daemon addon to schedule the script's execution as an automation):
```python
import detective.core as detective
import pandas as pd

db = detective.db_from_hass_config()

# The id numbers in the loop come from the statistics metadata table and correspond to the sensor statistics you want to correct

for idn in (1, 2, 3):
    df = pd.DataFrame(db.perform_query(f'SELECT * FROM "statistics" WHERE metadata_id={idn}'))
    df[9] = df[8] - df[8].shift()
    df[9] = df[9].fillna(0)
    df.loc[df[df[9] < 0].index, 9] = 0
    df[9] = df[9].cumsum()
    for stat_idn, value in zip(df[0], df[9]):
        db.perform_query(f'''
        UPDATE statistics
        SET sum = {value}
        WHERE id={stat_idn} 
        ''')
```
It is certainly not an optimized function as it will correct and recalculate all statistical history for these sensors and issues the update 1 value at a time.  So if you have a lot of statistical history, it could be slow.  But I am running on a raspberry pi 4 with sqlite database with about 4 months of statistical history for some sensors and it takes about 4 seconds to run, sufficiently fast for a script I won't use for long (assuming all of the statistical issues are fixed in the September release).  Your results may vary.  It is always risky to alter the database outside of normal home assistant operation, so be sure to take a backup and be careful.

**Comment by Zyell** [comment]
@magico13 Between the home assistant fix for the precision issues and your change of the state class to total_increasing, I think this issue is resolved.  I had to run my summation correction script one more time after the upgrade and things seem to be working properly since. :-)  Thank you so much for the changes!

@yodashut Did you find that the updates to the latest plugin version and homeassistant fixed things for you?

**Comment by yodashut** [comment]
After updating everything to the latest versions and resetting my energy config everything works great now!

Thanks for the update!
