### ISSUE TITLE
Missing Text on Integration Setup

### ISSUE THREAD

**Issue by thrasher204** [magico13/ha-emporia-vue#7]
When setting up the integration from the configuration add integration menu the inputs for username and password dont have any text indicating what they are. Not a big deal just an enhancement request also can the Emporia Icon be added to the integration?
![image](https://user-images.githubusercontent.com/30193480/85627523-7d44e880-b623-11ea-8a03-25c00ceb3ccc.png)

**Comment by magico13** [comment]
I looked briefly in the past to see if there was a way to add text to that but it didn't jump out at me. I'll give it another look next time I'm working on this. As for the icon, I'll have to be a bit careful about that since it could become a copyright problem if I user their logo. Since this isn't for profit it would probably be ok and I'd remove it at their request if it came down to that.

**Comment by magico13** [comment]
Fixed in v0.2.0
