### ISSUE TITLE
Undefined: SOURCE_IMPORT

### ISSUE THREAD

**Issue by Subtalime** [magico13/ha-emporia-vue#87]
I've had to install it manually by copying the component in the Config-Folder, since I for the life of me was unable to find any "3 dots" in current HA (core-2021.10.6).
In __init__.py (58) the constant SOURCE_IMPORT is undefined, hence the Plugin wont start. Where does this value come from or what should it contain?

**Comment by magico13** [comment]
The "3 dots" is referring to within the HACS menu, which if you're going to install anything manually I highly recommend just installing HACS (which is a manual install) and using that to install this.

If you still want to install this manually then it should just be dropping the emporia_vue folder into custom_components within your Home Assistant configuration folder. It must go within the custom_components folder for it to work correctly.

**Comment by magico13** [comment]
Here's the link for HACS, I definitely recommend installing HACS instead of doing a manual install of this. https://github.com/hacs/integration

**Comment by Subtalime** [comment]
Hi, thx for getting back to me. I did just drop it in the Components-Folder, however SOURCE_IMPORT comes as "undefined" in the Logfile.
This is what Home-Assistant looks to me... it's in a docker container, downloaded from ghcr.io/home-assistant/raspberrypi3-homeassistant:stable
Unfortunately there is no HACS in the Menu and also not in the integrations (see screenshot)
![image](https://user-images.githubusercontent.com/10029499/139963618-466a2046-6b82-4f60-8dac-5a718c8232cb.png)

**Comment by magico13** [comment]
HACS is a custom component so it also has to be put in the custom_components folder. Their install guide is going to be far more detailed than anything I can provide since it's a hugely popular component. If you get HACS working you'll have access to thousands of additional integrations, including this one.

I also run with a docker container but not the one you linked since I'm not using a Raspberry Pi. With my setup I have a volume mount for the configuration folder where configuration.yaml lives. In that same directory I have a custom_components folder and inside that is an emporia_vue folder (and also a HACS folder since that's also how HACS gets installed), then inside emporia_vue is the various .py files for this integration. If your file structure doesn't look the same then that's most likely the issue. 

![Screenshot_20211102-191749](https://user-images.githubusercontent.com/5289685/139964980-01b92753-5074-4d4d-b172-149d6842b3aa.png)

**Comment by Subtalime** [comment]
Sorry, I did delete my comment, but obviously too late ;)
I installed the requirements for HACS in my Docker-Engine, then it fired up successfully. HACS is now up and running, tomorrow I'll get back to your plugin and feed back if there are any further issues!
Thx for your help ;)

**Comment by Subtalime** [comment]
Welp, not looking too good. I installed it via HACS and it shows on HACS as installed (V0.70). However, it is not showing on HA Configuration and Integration. So, I decided to add the Login manually in the configuration.yaml by adding
`emporia_vue:
  email: <vue_email>
  password: <vue_password>
`
restarting HA and the log shows:
2021-11-03 22:07:33 ERROR (MainThread) [homeassistant.setup] Error during setup of component emporia_vue
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 254, in _async_setup_component
    result = await task
  File "/config/custom_components/emporia_vue/__init__.py", line 58, in async_setup
    context={"source": SOURCE_IMPORT},
NameError: name 'SOURCE_IMPORT' is not defined

**Comment by magico13** [comment]
I don't think that variable is needed so I just removed it and am doing some testing. Since you've got HACS installed, go into it and install version 0.7.1 and see if that helps. Since it just released you might have to update the info for the integration from the "3 dots" menu before it will see it. Make sure to restart Home Assistant afterward, also remove your credentials from the configuration.yaml and set it up through the UI since there are some check boxes you'll want to fill out to determine which sensors you want to use.

Also it looks like the Emporia API is acting up a bit today so if you don't see all the sensors once it finally loads, you may have to reload the integration from HA's integration menu for it to see all the devices/sensors. I've been getting a lot of 500 errors since they sent out the email about the web view.

**Comment by Subtalime** [comment]
Thx, updated to this version and the log stayed clear... but HA is still firing up "waiting for Emporia-Vue"...
now after 5 minutes (still not up), the log shows
`2021-11-03 23:12:11 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 151, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 169, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 722, in async_create_flow
    raise KeyError("Context not set or doesn't have a source set")
KeyError: "Context not set or doesn't have a source set"
2021-11-03 23:13:10 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: emporia_vue
`

**Comment by Subtalime** [comment]
Oh, and it doesn't show on HA's integration... only on HACS
![image](https://user-images.githubusercontent.com/10029499/140231924-ef7534f1-5653-45e2-b62d-b3fa85b1e592.png)
![image](https://user-images.githubusercontent.com/10029499/140231968-23c54738-5c4d-47aa-9d92-8d1c2480a232.png)

**Comment by magico13** [comment]
Apparently the context requires a source but SOURCE_IMPORT isn't valid. I'm really not sure why you're having issues with this but nobody else has reported it before. Let me try setting that key to some other value.

**Comment by blackburn42330** [comment]
After installing in hacs, did you add it in the integrations page?

**Comment by Subtalime** [comment]
it doesn't show on the Integration page.
![image](https://user-images.githubusercontent.com/10029499/140232713-4964be88-e726-4340-90a7-01cd3ce185f0.png)

**Comment by magico13** [comment]
Ok, I figured out where SOURCE_IMPORT is supposed to come from and added that into the imports. v0.7.2 hopefully actually fixes it this time.

Once you update in HACS, reboot, then check the integrations page again. It should hopefully be available to add at that point. Some times you need to reload the browser cache with ctrl-shift-r or shift-F5.

**Comment by Subtalime** [comment]
Magic!!! That did it!!!
Your help and effort is much appreciated! Now I get to play with it!
