### ISSUE TITLE
Feature request: seconds entity (for faster automations)

### ISSUE THREAD

**Issue by jkoop** [magico13/ha-emporia-vue#89]
There are month, day, minute entities. I request a second entity so my automations can react faster.

**Comment by magico13** [comment]
There used to be a seconds entity but I was asked by Emporia to remove it due to the number of requests against their servers from people using this plugin far outweighing their other users. They asked me to keep the number of requests below 2000 a day which means minute level data is the best I can provide until they decide to provide another way to access the data more frequently.

https://github.com/magico13/PyEmVue/issues/19
