### ISSUE TITLE
state_class is missing for hourly data

### ISSUE THREAD

**Issue by jbrukardt** [magico13/ha-emporia-vue#94]
For Emporia Vue sensors, it seems the state_class may also not be set for the hourly sensor properly for long term statistics.   When trying to add the hourly sensor to Home Assistant Energy, it doesnt show up on the list, and links to this page 

https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

For example:  sensor.emporianame_123_1d and sensor.emporianame_123_1mon both show up as selectable in the energy dashboard, and both appear to be total_increasing, as the energy use builds up

sensor.emporianame_123_1min does not show up, and it seems to be a series of instantaneous reads (measurement).

   
It looks like the root cause may be the the Energy dashboard requires a measurement unit of KwH (needs a unit of time), and the 1M readings are solely in W.

**Comment by jbrukardt** [comment]
As a side note, it seems this can be remedied by using the Riemann sum integration built into HA, but itd be nice if there was a default sensor too for finer granularity than the 1hr sensor.

**Comment by magico13** [comment]
There is no 1 hour sensor in this integration. The monthly data is updated hourly, the daily data is updated every fifteen minutes or so, and the minute data (which is the average *power* over the last minute, not the *energy* used) is updated each minute. The minute data is actually integrated into the daily data automatically so if you use the 1D sensors for the energy dashboard you will have the best results.

All of the state classes are correct for the type of data they represent, which matches the representations within the Emporia app (minute = power = kW, day = energy = kWh).

The Home Assistant energy dashboard only works for energy data, not power data so the 1m sensor will not be available there. You *can* get a stats view for the peak/min/avg power off the 1min sensors because statistic generation is enabled for them.

**Comment by jbrukardt** [comment]
Sorry, you are correct.  I mis-spoke and i meant the 1 minute sensor, which you have explained well.   Is there any sensor exposed with greater granularity for energy than the daily sensor which appears to update hourly in the energy dashboard.  Its difficult to track individual appliance use with only the 1hr rollups

**Comment by magico13** [comment]
The Home Assistant energy dashboard will only update hourly, there's no getting around that unless it is rewritten. You can of course use the daily sensors in any other dashboard, for instance I use the history graph with them quite often, to get a general idea of usage in my home.


![Screenshot_20211214-184944](https://user-images.githubusercontent.com/5289685/146097469-190cd03d-ce9d-48fe-8d1e-40110b4b5c19.png)
![Screenshot_20211214-185121](https://user-images.githubusercontent.com/5289685/146097618-02260317-f884-41b2-84fc-75a44e728899.png)
